apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL:  'https://prometheus-community.github.io/helm-charts'
      chart:  prometheus
      targetRevision: 22.6.2
      helm:
          valueFiles:
          - "$myRepo/prometheusValues.yaml"
    - repoURL:  'git@github.com:BarYohaiVaknin/codeExamples/ArgoCD/a-o-a.git'
      ref: myRepo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
      automated: {}
      syncOptions:
        - ServerSideApply=true