server:
  ingress: 
    enabled: true
    ingressClassName: nginx
    annotations: {"nginx.ingress.kubernetes.io/rewrite-target": "/$2"}
    hosts:
      - my.dns.com
    path: "/prometheus(/|$)(.*)"
  extraFlags: 
    - web.enable-lifecycle
    - web.route-prefix=/
    - web.external-url=http://my.dns.com/prometheus

  persistentVolume:
    existingClaim: prometheus-pvc
    size: 10Gi


extraScrapeConfigs: | 
  - job_name: 'basic-node-exporter'
    metrics_path: '/metrics'
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['10.0.0.207:9100']
  - job_name: 'custom-metrics'
    metrics_path: /
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['10.0.0.207:9101']